version: "3.7"

services:
  website:
    build: website
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - default

  http_check_producer:
    build: http_check_producer
    depends_on:
      - website
    command: ["http_check_consumer", "-d", "run", "--url", "${CHECK_URL}"]
    networks:
      - default

  http_check_consumer:
    build: http_check_consumer
    networks:
      - default
    command: ["http_check_consumer", "-d", "run"]


networks:
  default: