# Install all dependencies to perform integration tests:
# * http_check_producer
# * http_check_consumer
# * (py)test dependencies
FROM python:3.7-slim

RUN apt-get update \
    && apt-get install -y libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

COPY http_check_producer/wait-for-it.sh /wait-for-it.sh
COPY avro_schema /avro_schema

WORKDIR /app

COPY ./http_check_producer/http_check_producer/requirements.txt requirements_producer.txt
COPY ./http_check_consumer/http_check_consumer/requirements.txt requirements_consumer.txt
COPY ./integration_tests/requirements_test.txt requirements_test.txt

RUN pip install -r requirements_producer.txt
RUN pip install -r requirements_consumer.txt
RUN pip install -r requirements_test.txt

COPY ./http_check_producer/http_check_producer http_check_producer/
COPY ./http_check_consumer/http_check_consumer http_check_consumer/

WORKDIR /app/http_check_producer
RUN python setup.py install

WORKDIR /app/http_check_consumer
RUN python setup.py install

COPY ./integration_tests /app/integration_tests
WORKDIR /app/integration_tests
